apiVersion: v1
kind: Service
metadata:
  name: go-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: go-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
        - name: go-example
          image: alexon1234/poc_go_example:latest
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_DB
              value: "0"
            - name: REDIS_HOST
              value: "redis-master:6379"
            - name: REDIS_PASSWORD
              value: "lu42hoShVj"
            - name: AMQP_HOST
              value: "amqp://admin:admin@rabbitmq.default.svc.cluster.local:5672/"
