apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: simple-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: blahblah.com
      http:
        paths:
          - path: /
            backend:
              serviceName: go-service
              servicePort: 8080
